name: BasicEconomy
version: '${project.version}'
main: me.wacko.basiceconomy.BasicEconomy
api-version: '1.20'

#depend:
  #- [VaultAPI]

commands:
  pv:
    usage: /<command>
    description: open your personal vault
  shop:
    usage: /<command>
    description: opens the shop
  bal:
    usage: /<command>
    description: displays a user's balance
