name: BasicEconomy
version: '${project.version}'
main: me.wacko.basiceconomy.BasicEconomy
api-version: '1.20'

#depend:
  #- [VaultAPI]

commands:
  playervault:
    description: open your personal vault
    aliases:
      - pv
  shop:
    description: opens the shop
  balance:
    description: displays a user's balance
    aliases:
      - bal
  auctions:
    description: opens the auctions gui
    aliases:
      - ah

